--[[

Test Sine Wave Generator
by Mark Boyd
v 1.0
March 28, 2023
http://www.markboyd.dev

Inputs: n/a
Outputs: Audio

This script generates a sine wave at a set frequency.

You can change the frequency by changing the value of the "hz" variable.

The sampleRate is set to 44100, but you must set it to match the sample
rate of the audio device you are using.

The phase variable is used to keep track of the current position in the 
sine wave. The phase is incremented by the frequency divided by the 
sample rate. The phase is then checked to see if it is greater than or 
equal to 1. If it is, the phase is reset to 0. This is done to keep the 
phase value between 0 and 1.

The sine wave is then generated by using the phase value as the input to
the math.sin function. The output of the math.sin function is then
stored in the Audio table.

--]]

hz = 440
sampleRate = 44100
phase = 0

function process(frames)
    for i=1,frames do
        phase = phase + (hz / sampleRate)

        if phase >= 1 then phase = 0 end
        
        Audio[i] = math.sin(2 * math.pi * phase)
    end
end
